version: "3"
services:
  apppython:
    image: api-actor-python
    ports:
      - "5000:5000"
    depends_on:
      - db
  app:
    image: spring-movies
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"


